### ISSUE TITLE
Unrecognized Line

### ISSUE THREAD

**Issue by jchene** [42School/norminette#317]
When i norminette my file i get the error:
`Error: Unrecognized line (46, 59) while parsing [<IDENTIFIER=O_RDONLY>, <RPARENTHESIS>]`
Same problem happens when i replace O_RDONLY by it's value ("00") or by 0.

My code:
```
int	set_input_fds(char **argv, int i)
{
	if (i == 0)
	{
		get_data(NULL)->files_fds[INFILE] = open(argv[1], O_RDONLY);
		if (get_data(NULL)->files_fds[INFILE] < 0)
			perror("pipex: open");
		get_exec(NULL)->in_fds[READ] = get_data(NULL)->files_fds[INFILE];
		get_exec(NULL)->in_fds[WRITE] = -1;
	}
	else
	{
		get_exec(NULL)->in_fds[READ] = get_data(NULL)->pipes[i - 1][READ];
		get_exec(NULL)->in_fds[WRITE] = get_data(NULL)->pipes[i - 1][WRITE];
	}
	return (0);
}
```

**Additional infos**
 - OS: Ubuntu 20.04 LTS
 - python --version: 2.7.18
 - python3 --version: 3.8.10
 - norminette -v: 3.3.51

**Comment by jchene** [comment]
Hello, i'm Jchene from 42Paris.
Norminette doesn't seems to like singletons and the "function()->"
formulation.
I have succeeded to bypass this error by adding some parenthesis like this:
"(function())->"
Best regards
Jchene

**Comment by mjy9088** [comment]
I circumvented it in same way too. thanks :)

**Comment by NiumXp** [comment]
This issue was fixed in #412.

**Comment by ayoubelmohamedi** [comment]
@NiumXp  it isn't fixed yet. I faced the same problem with this case
`getcore()->env[i] = ft_strjoin_m(tmpstr, env_list->value);`
apparently, adding parenthesis to variable resolves the issue
` (getcore()->env[i]) = ft_strjoin_m(tmpstr, env_list->value);`
This is with latest version of norminette 3.3.55
